import type {
  CalendarEvent,
  DashboardData,
  Integration,
  Note,
  StorageFile,
  StorageUsage,
} from "./models";
const today = new Intl.DateTimeFormat("en-CA", {
  timeZone: "Asia/Kolkata",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
}).format(new Date());
export const demoFiles: StorageFile[] = [
  {
    id: "f1",
    provider: "drive",
    providerId: "demo1",
    name: "Brand guidelines.pdf",
    virtualPath: "/Documents",
    mimeType: "application/pdf",
    size: 2400000,
    modifiedAt: new Date().toISOString(),
  },
  {
    id: "f2",
    provider: "r2",
    providerId: "demo2",
    name: "Homepage explorations.fig",
    virtualPath: "/Design",
    mimeType: "application/octet-stream",
    size: 8400000,
    modifiedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "f3",
    provider: "r2",
    providerId: "demo3",
    name: "Weekend in the mountains.jpg",
    virtualPath: "/Photos",
    mimeType: "image/jpeg",
    size: 3200000,
    modifiedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "f4",
    provider: "drive",
    providerId: "demo4",
    name: "Ideas for the next big thing.md",
    virtualPath: "/Documents",
    mimeType: "text/markdown",
    size: 4200,
    modifiedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "f5",
    provider: "r2",
    providerId: "demo5",
    name: "Portfolio backup.zip",
    virtualPath: "/Archives",
    mimeType: "application/zip",
    size: 182000000,
    modifiedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];
export const demoUsage: StorageUsage[] = [
  { provider: "r2", label: "Cloudflare R2", used: 6.8e9, capacity: null },
  { provider: "drive", label: "Google Drive", used: 8.2e9, capacity: 15e9 },
];
export const demoNotes: Note[] = [
  {
    id: "n1",
    title: "Little ideas, big possibilities",
    body: "A space to collect the things that spark something.\n\n→ A tiny tool for a daily problem\n→ More time making, less time managing\n→ Build something just for the fun of it",
    color: "sage",
    pinned: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "n2",
    title: "This week’s focus",
    body: "Keep it simple. Ship something small.\n\nFinish the portfolio refresh\nOrganize the design archive\nTake a proper screen-free Sunday",
    color: "lavender",
    pinned: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "n3",
    title: "Things worth remembering",
    body: "Good things take a little time.\n\nMake room for curiosity. Write the idea down before it disappears.",
    color: "sand",
    pinned: false,
    updatedAt: new Date().toISOString(),
  },
];
export const demoEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Design catch-up",
    start: `${today}T14:00:00+05:30`,
    end: `${today}T14:45:00+05:30`,
    color: "lavender",
    location: "Google Meet",
  },
  {
    id: "e2",
    title: "A little time to build",
    start: `${today}T16:00:00+05:30`,
    end: `${today}T17:30:00+05:30`,
    color: "sage",
    location: "Focus time",
  },
  {
    id: "e3",
    title: "Evening walk",
    start: `${today}T18:30:00+05:30`,
    end: `${today}T19:00:00+05:30`,
    color: "sand",
    location: "Outside, finally",
  },
];
export const demoDashboard: DashboardData = {
  sites: [
    {
      id: "s1",
      name: "Personal portfolio",
      url: "akshat.dev",
      status: "healthy",
      visitors: 1284,
      change: 12.8,
      series: [15, 22, 19, 31, 24, 35, 30, 46, 41, 55, 49, 68],
    },
    {
      id: "s2",
      name: "Side project",
      url: "playground.akshat.dev",
      status: "healthy",
      visitors: 846,
      change: 8.2,
      series: [10, 13, 11, 20, 18, 22, 19, 28, 25, 32, 30, 38],
    },
    {
      id: "s3",
      name: "Notes & thoughts",
      url: "notes.akshat.dev",
      status: "healthy",
      visitors: 298,
      change: 5.4,
      series: [8, 12, 10, 13, 11, 18, 16, 24, 19, 25, 21, 30],
    },
  ],
  events: demoEvents,
  activity: [
    {
      id: "a1",
      title: "Portfolio is looking fresh",
      detail: "Deployment completed · Cloudflare",
      time: "12 min ago",
      type: "deploy",
    },
    {
      id: "a2",
      title: "Brand guidelines.pdf added",
      detail: "Documents · Google Drive",
      time: "38 min ago",
      type: "file",
    },
    {
      id: "a3",
      title: "A little progress, committed",
      detail: "feat: update homepage · GitHub",
      time: "1 hour ago",
      type: "commit",
    },
  ],
};
export const demoIntegrations: Integration[] = [
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Infrastructure",
    description: "Your sites, Workers, and traffic in one place.",
    status: "demo",
  },
  {
    id: "r2",
    name: "Cloudflare R2",
    category: "Storage",
    description: "A home for files, backups, and everything else.",
    status: "demo",
  },
  {
    id: "drive",
    name: "Google Drive",
    category: "Storage",
    description: "Your Drive files, without the tab hopping.",
    status: "demo",
  },
  {
    id: "calendar",
    name: "Google Calendar",
    category: "Calendar",
    description: "A little more space to see what’s ahead.",
    status: "demo",
  },
  {
    id: "github",
    name: "GitHub",
    category: "Development",
    description: "Keep your projects and progress close by.",
    status: "not_configured",
  },
];
